{{ if .Values.dpr }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dpr
  namespace: kube-system
  labels:
    app: {{ .Release.Name }}
    cloud: private
data:
  DOCKER_PRIVATE_REGISTRY_SERVER: {{ .Values.dpr.server | b64enc }}
  DOCKER_PRIVATE_REGISTRY_USER: {{ .Values.dpr.user | b64enc }}
  DOCKER_PRIVATE_REGISTRY_PASSWORD: {{ .Values.dpr.password | b64enc }}
type: Opaque
{{ end }}
---
{{ if .Values.ecr }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ecr
  namespace: kube-system
  labels:
    app: {{ .Release.Name }}
    cloud: ecr
data:
  AWS_ACCESS_KEY_ID: {{ .Values.ecr.accessKeyID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.ecr.secretAccessKey | b64enc }}
  AWS_SESSION_TOKEN: {{ default "" .Values.ecr.sessionToken | b64enc }}
  aws-account: {{ .Values.ecr.account | b64enc }}
  aws-region: {{ .Values.ecr.region | b64enc }}
  aws-assume-role: {{ default "" .Values.ecr.assumeRole | b64enc }}
type: Opaque
{{ end }}
---
{{ if .Values.gcr }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gcr
  namespace: kube-system
  labels:
    app: {{ .Release.Name }}
    cloud: gcr
data:
  application_default_credentials.json: {{ .Values.gcr.applicationDefaultCredentials | b64enc }}
  gcrurl: {{ .Values.gcr.url | b64enc }}
type: Opaque
{{ end }}
---
{{ if .Values.acr }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-acr
  namespace: kube-system
  labels:
    app: {{ .Release.Name }}
    cloud: acr
data:
  ACR_URL: {{ .Values.acr.url | b64enc }}
  ACR_CLIENT_ID: {{ .Values.acr.clientID | b64enc }}
  ACR_PASSWORD: {{ .Values.acr.password | b64enc }}
type: Opaque
{{ end }}